public class RMGDataController {
private String Name;
private String Attain_desired_role_ratios;
private String Readiness_to_staff_new_projects;
private String Resource_forecast_planning_CP_AD;
private String Resource_forecast_planning_CP_KK;
private String Resource_forecast_planning_CP_PS;
private String Resource_forecast_planning_CP_RP;
private String Resource_forecast_planning_Sales_DIT;
private String Resource_forecast_planning_Sales_Mani;
private String Resource_forecast_planning_Sales_Satya;
private String Resource_forecast_planning_Sales_VK;
private String Utilization_rate;
private String Resource_forecast_planning_Sales_Overall;
private String Month;
private String Year;

public String getName() {
return Name;
}
public void setName(String firstName) {
this.Name= firstName;
}
public String getAttain_desired_role_ratios() {
return Attain_desired_role_ratios;
}
public void setAttain_desired_role_ratios(String firstName) {
this.Name= Attain_desired_role_ratios;
}
public String getReadiness_to_staff_new_projects() {
return Readiness_to_staff_new_projects;
}
public void setReadiness_to_staff_new_projects(String firstName) {
this.Readiness_to_staff_new_projects= firstName;
}
public String getResource_forecast_planning_CP_AD() {
return Resource_forecast_planning_CP_AD;
}
public void setResource_forecast_planning_CP_AD(String firstName) {
this.Resource_forecast_planning_CP_AD= firstName;
}
public String getResource_forecast_planning_CP_KK() {
return Resource_forecast_planning_CP_KK;
}
public void setResource_forecast_planning_CP_KK(String firstName) {
this.Resource_forecast_planning_CP_KK= firstName;
}
public String getResource_forecast_planning_CP_PS() {
return Resource_forecast_planning_CP_PS;
}
public void setResource_forecast_planning_CP_PS(String firstName) {
this.Resource_forecast_planning_CP_PS= firstName;
}
public String getResource_forecast_planning_CP_RP() {
return Resource_forecast_planning_CP_RP;
}
public void setResource_forecast_planning_CP_RP(String firstName) {
this.Resource_forecast_planning_CP_RP= firstName;
}
public String getResource_forecast_planning_Sales_DIT() {
return Resource_forecast_planning_Sales_DIT;
}
public void setResource_forecast_planning_Sales_DIT(String firstName) {
this.Resource_forecast_planning_Sales_DIT= firstName;
}
public String getResource_forecast_planning_Sales_Mani() {
return Resource_forecast_planning_Sales_Mani;
}
public void setResource_forecast_planning_Sales_Mani(String firstName) {
this.Resource_forecast_planning_Sales_Mani= firstName;
}
public String getResource_forecast_planning_Sales_Satya() {
return Resource_forecast_planning_Sales_Satya;
}
public void setResource_forecast_planning_Sales_Satya(String firstName) {
this.Resource_forecast_planning_Sales_Satya= firstName;
}
public String getResource_forecast_planning_Sales_VK() {
return Resource_forecast_planning_Sales_VK;
}
public void setResource_forecast_planning_Sales_VK(String firstName) {
this.Resource_forecast_planning_Sales_VK= firstName;
}
public String getUtilization_rate() {
return Utilization_rate;
}
public void setUtilization_rate(String firstName) {
this.Utilization_rate= firstName;
}
public String getResource_forecast_planning_Sales_Overall() {
return Resource_forecast_planning_Sales_Overall;
}
public void setResource_forecast_planning_Sales_Overall(String firstName) {
this.Resource_forecast_planning_Sales_Overall= firstName;
}
public String getMonth() {
return Month;
}
public void setMonth(String firstName) {
this.Month= firstName;
}
public String getYear() {
return Year;
}
public void setYear(String firstName) {
this.Year= firstName;
}

static testMethod void myTest() {


RMGDataController controller = new RMGDataController();
controller.getName();
controller.setName('abc');
controller.getAttain_desired_role_ratios();
controller.setAttain_desired_role_ratios('abc');
controller.getReadiness_to_staff_new_projects();
controller.setReadiness_to_staff_new_projects('abc');
controller.getResource_forecast_planning_CP_AD();
controller.setResource_forecast_planning_CP_AD('abc');
controller.getResource_forecast_planning_CP_KK();
controller.setResource_forecast_planning_CP_KK('abc');
controller.getResource_forecast_planning_CP_PS();
controller.setResource_forecast_planning_CP_PS('abc');
controller.getResource_forecast_planning_CP_RP();
controller.setResource_forecast_planning_CP_RP('abc');
controller.getResource_forecast_planning_Sales_DIT();
controller.setResource_forecast_planning_Sales_DIT('abc');
controller.getResource_forecast_planning_Sales_Mani();
controller.setResource_forecast_planning_Sales_Mani('abc');
controller.getResource_forecast_planning_Sales_Satya();
controller.setResource_forecast_planning_Sales_Satya('abc');
controller.getResource_forecast_planning_Sales_VK();
controller.setResource_forecast_planning_Sales_VK('abc');
controller.getResource_forecast_planning_Sales_Overall();
controller.setResource_forecast_planning_Sales_Overall('abc');
controller.getMonth();
controller.setMonth('abc');
controller.getYear();
controller.setYear('abc');


}
}