public class SalesDataController {
ApexPages.StandardController controller{get; set;}
private String Achieve_sales_process_compliance_CL;
private String Achieve_sales_process_compliance_E_biz;
private String Achieve_sales_process_compliance_E_Med;

private String CP_AD;
private String CP_KK;
private String CP_ps;
private String CP_RP;

private String Name;
private String Month;
private String Year;




private String Customer_perception_of_Tavant;
private String number_of_client_visits_by_GDMs_SPMs;
private String Number_of_new_clients_in_CLP;
private String Number_of_new_clients_in_EbizP;
private String Number_of_new_clients_in_EmedP;
private String Number_of_new_clients_in_SOPSP;
private String Number_of_new_customers_in_CLP;
private String Number_of_new_customers_in_EbizP;
private String Number_of_new_customers_in_EmedP;
private String Number_of_new_customers_in_SOPSP;
private String Number_of_qualified_leads_for_CLP;
private String Number_of_qualified_leads_for_CMP;
private String Number_of_qualified_leads_for_EbizP;
private String Number_of_qualified_leads_for_EmedP;
private String Number_of_qualified_leads_for_SOPSP;
private String numbof_whitepapers_case_studies_marketin;

private String Sales_effectiveness_for_the_organization;

private String Total_IT_budget_of_all_clients_in_CL;
private String Total_IT_budget_of_all_clients_in_CMP;
private String Total_IT_budget_of_all_clients_in_e_biz;
private String Total_IT_budget_of_all_clients_in_e_med;
private String Total_IT_budget_of_all_clients_in_SOPS;




public String getCustomer_perception_of_Tavant() {
return Customer_perception_of_Tavant;
}
public void setCustomer_perception_of_Tavant(String add) {
this.Customer_perception_of_Tavant=add;
}



public String getAchieve_sales_process_compliance_CL() {
return Achieve_sales_process_compliance_CL;
}
public void setAchieve_sales_process_compliance_CL(String firstName) {
this.Achieve_sales_process_compliance_CL= firstName;
}

public String getAchieve_sales_process_compliance_E_biz() {
return Achieve_sales_process_compliance_E_biz;
}
public void setAchieve_sales_process_compliance_E_biz(String firstName) {
this.Achieve_sales_process_compliance_E_biz= firstName;
}
public String getAchieve_sales_process_compliance_E_Med() {
return Achieve_sales_process_compliance_E_Med;
}
public void setAchieve_sales_process_compliance_E_Med(String firstName) {
this.Achieve_sales_process_compliance_E_Med= firstName;
}

public String getCP_AD() {
return CP_AD;
}
public void setCP_AD(String firstName) {
this.CP_AD= firstName;
}
public String getCP_KK() {
return CP_KK;
}
public void setCP_KK(String firstName) {
this.CP_KK= firstName;
}
public String getCP_ps() {
return CP_ps;
}
public void setCP_ps(String firstName) {
this.CP_ps= firstName;
}

public String getCP_RP() {
return CP_RP;
}
public void setCP_RP(String add) {
this.CP_RP=add;
}





public String getMonth() {
return Month;
}
public void setMonth(String add) {
this.Month=add;
}
public String getYear() {
return Year;
}
public void setYear(String add) {
this.Year=add;
}




public String getTotal_IT_budget_of_all_clients_in_e_med() {
return Total_IT_budget_of_all_clients_in_e_med;
}
public void setTotal_IT_budget_of_all_clients_in_e_med(String add) {
this.Total_IT_budget_of_all_clients_in_e_med=add;
}

public String getTotal_IT_budget_of_all_clients_in_SOPS() {
return Total_IT_budget_of_all_clients_in_SOPS;
}
public void setTotal_IT_budget_of_all_clients_in_SOPS(String add) {
this.Total_IT_budget_of_all_clients_in_SOPS=add;
}


public String getTotal_IT_budget_of_all_clients_in_CL() {
return Total_IT_budget_of_all_clients_in_CL;
}
public void setTotal_IT_budget_of_all_clients_in_CL(String add) {
this.Total_IT_budget_of_all_clients_in_CL=add;
}


public String getTotal_IT_budget_of_all_clients_in_CMP() {
return Total_IT_budget_of_all_clients_in_CMP;
}
public void setTotal_IT_budget_of_all_clients_in_CMP(String add) {
this.Total_IT_budget_of_all_clients_in_CMP=add;
}


public String getTotal_IT_budget_of_all_clients_in_e_biz() {
return Total_IT_budget_of_all_clients_in_e_biz;
}
public void setTotal_IT_budget_of_all_clients_in_e_biz(String add) {
this.Total_IT_budget_of_all_clients_in_e_biz=add;
}
public String getSales_effectiveness_for_the_organization() {
return Sales_effectiveness_for_the_organization;
}
public void setSales_effectiveness_for_the_organization(String add) {
this.Sales_effectiveness_for_the_organization=add;
}





public String getnumber_of_client_visits_by_GDMs_SPMs() {
return number_of_client_visits_by_GDMs_SPMs;
}
public void setnumber_of_client_visits_by_GDMs_SPMs(String add) {
this.number_of_client_visits_by_GDMs_SPMs=add;
}


public String getNumber_of_new_clients_in_CLP() {
return Number_of_new_clients_in_CLP;
}
public void setNumber_of_new_clients_in_CLP(String add) {
this.Number_of_new_clients_in_CLP=add;
}


public String getNumber_of_new_clients_in_EbizP() {
return Number_of_new_clients_in_EbizP;
}
public void setNumber_of_new_clients_in_EbizP(String add) {
this.Number_of_new_clients_in_EbizP=add;
}

public String getNumber_of_new_clients_in_EmedP() {
return Number_of_new_clients_in_EmedP;
}
public void setNumber_of_new_clients_in_EmedP(String add) {
this.Number_of_new_clients_in_EmedP=add;
}


public String getNumber_of_new_clients_in_SOPSP() {
return Number_of_new_clients_in_SOPSP;
}
public void setNumber_of_new_clients_in_SOPSP(String add) {
this.Number_of_new_clients_in_SOPSP=add;
}


public String getNumber_of_new_customers_in_CLP() {
return Number_of_new_customers_in_CLP;
}
public void setNumber_of_new_customers_in_CLP(String add) {
this.Number_of_new_customers_in_CLP=add;
}


public String getNumber_of_new_customers_in_EbizP() {
return Number_of_new_customers_in_EbizP;
}
public void setNumber_of_new_customers_in_EbizP(String add) {
this.Number_of_new_customers_in_EbizP=add;
}


public String getNumber_of_new_customers_in_EmedP() {
return Number_of_new_customers_in_EmedP;
}
public void setNumber_of_new_customers_in_EmedP(String add) {
this.Number_of_new_customers_in_EmedP=add;
}

public String getNumber_of_new_customers_in_SOPSP() {
return Number_of_new_customers_in_SOPSP;
}
public void setNumber_of_new_customers_in_SOPSP(String add) {
this.Number_of_new_customers_in_SOPSP=add;
}


public String getNumber_of_qualified_leads_for_CLP() {
return Number_of_qualified_leads_for_CLP;
}
public void setNumber_of_qualified_leads_for_CLP(String add) {
this.Number_of_qualified_leads_for_CLP=add;
}

public String getNumber_of_qualified_leads_for_CMP() {
return Number_of_qualified_leads_for_CMP;
}
public void setNumber_of_qualified_leads_for_CMP(String add) {
this.Number_of_qualified_leads_for_CMP=add;
}

public String getNumber_of_qualified_leads_for_EbizP() {
return Number_of_qualified_leads_for_EbizP;
}
public void setNumber_of_qualified_leads_for_EbizP(String add) {
this.Number_of_qualified_leads_for_EbizP=add;
}

public String getNumber_of_qualified_leads_for_EmedP() {
return Number_of_qualified_leads_for_EmedP;
}
public void setNumber_of_qualified_leads_for_EmedP(String add) {
this.Number_of_qualified_leads_for_EmedP=add;
}


public String getNumber_of_qualified_leads_for_SOPSP() {
return Number_of_qualified_leads_for_SOPSP;
}
public void setNumber_of_qualified_leads_for_SOPSP(String add) {
this.Number_of_qualified_leads_for_SOPSP=add;
}


public String getnumbof_whitepapers_case_studies_marketin() {
return numbof_whitepapers_case_studies_marketin;
}
public void setnumbof_whitepapers_case_studies_marketin(String add) {
this.numbof_whitepapers_case_studies_marketin=add;
}


















static testMethod void myTest() {


SalesDataController controller = new SalesDataController();



controller.getCustomer_perception_of_Tavant();
controller.setCustomer_perception_of_Tavant('abc');
controller.getAchieve_sales_process_compliance_CL();
controller.setAchieve_sales_process_compliance_CL('abc');
controller.getAchieve_sales_process_compliance_E_biz();
controller.setAchieve_sales_process_compliance_E_biz('abc');
controller.getAchieve_sales_process_compliance_E_Med();
controller.setAchieve_sales_process_compliance_E_Med('abc');
controller.getCP_AD();
controller.setCP_AD('abc');
controller.getCP_KK();
controller.setCP_KK('abc');
controller.getCP_ps();
controller.setCP_ps('abc');
controller.getCP_ps();
controller.setCP_ps('abc');
controller.getCP_RP();
controller.setCP_RP('abc');


controller.getMonth();
controller.setMonth('abc');
controller.getYear();
controller.setYear('abc');


controller.getCustomer_perception_of_Tavant();
controller.setCustomer_perception_of_Tavant('abc');



controller.getnumber_of_client_visits_by_GDMs_SPMs();
controller.setnumber_of_client_visits_by_GDMs_SPMs('abc');
controller.getNumber_of_new_clients_in_CLP();
controller.setNumber_of_new_clients_in_CLP('abc');
controller.getNumber_of_new_clients_in_EbizP();
controller.setNumber_of_new_clients_in_EbizP('abc');
controller.getNumber_of_new_clients_in_EmedP();
controller.setNumber_of_new_clients_in_EmedP('abc');
controller.getNumber_of_new_clients_in_SOPSP();
controller.setNumber_of_new_clients_in_SOPSP('abc');
controller.getNumber_of_new_customers_in_CLP();
controller.setNumber_of_new_customers_in_CLP('abc');
controller.getNumber_of_new_customers_in_EbizP();
controller.setNumber_of_new_customers_in_EbizP('abc');
controller.getNumber_of_new_customers_in_EmedP();
controller.setNumber_of_new_customers_in_EmedP('abc');
controller.getNumber_of_new_customers_in_SOPSP();
controller.setNumber_of_new_customers_in_SOPSP('abc');
controller.getNumber_of_qualified_leads_for_CLP();
controller.setNumber_of_qualified_leads_for_CLP('abc');
controller.getNumber_of_qualified_leads_for_CMP();
controller.setNumber_of_qualified_leads_for_CMP('abc');
controller.getNumber_of_qualified_leads_for_EbizP();
controller.setNumber_of_qualified_leads_for_EbizP('abc');
controller.getNumber_of_qualified_leads_for_EmedP();
controller.setNumber_of_qualified_leads_for_EmedP('abc');
controller.getNumber_of_qualified_leads_for_SOPSP();
controller.setNumber_of_qualified_leads_for_SOPSP('abc');
controller.getnumbof_whitepapers_case_studies_marketin();
controller.setnumbof_whitepapers_case_studies_marketin('abc');

controller.getSales_effectiveness_for_the_organization();
controller.setSales_effectiveness_for_the_organization('abc');

controller.getTotal_IT_budget_of_all_clients_in_CL();
controller.setTotal_IT_budget_of_all_clients_in_CL('abc');
controller.getTotal_IT_budget_of_all_clients_in_CMP();
controller.setTotal_IT_budget_of_all_clients_in_CMP('abc');
controller.getTotal_IT_budget_of_all_clients_in_e_biz();
controller.setTotal_IT_budget_of_all_clients_in_e_biz('abc');
controller.getTotal_IT_budget_of_all_clients_in_e_med();
controller.setTotal_IT_budget_of_all_clients_in_e_med('abc');
controller.getTotal_IT_budget_of_all_clients_in_SOPS();
controller.setTotal_IT_budget_of_all_clients_in_SOPS('abc');

}
}